"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createServerSupabase } from "@/lib/supabase/server";
import { getActiveWorkspace } from "@/lib/auth/workspace";
import { dateString } from "@/lib/schemas/common";
import { normalizeOrderedIds } from "@/lib/execution-order";
import type { ActionResult } from "@/features/sessions/actions";

function revalidateTodayData() {
  revalidatePath("/today");
  revalidatePath("/history");
  revalidatePath("/progress");
  revalidatePath("/plan");
  revalidatePath("/reviews");
  revalidatePath("/courses");
  revalidatePath("/assessments");
}

const saveOrderSchema = z.object({
  date: dateString,
  orderedItemIds: z.array(
    z.union([
      z.string(),
      z.object({
        id: z.string(),
        type: z.string().optional(),
      }),
    ])
  ),
});

/**
 * Saves the custom daily execution order for a specific workspace and date.
 * Does NOT alter or mutate original study plan items or plan versions.
 */
export async function saveDailyExecutionOrder(
  input: z.infer<typeof saveOrderSchema>
): Promise<ActionResult> {
  const parsed = saveOrderSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" };
  }

  const workspace = await getActiveWorkspace();
  if (!workspace) return { ok: false, error: "ไม่พบ workspace" };

  const supabase = await createServerSupabase();
  const normalizedIds = normalizeOrderedIds(parsed.data.orderedItemIds);

  const { error } = await supabase.from("daily_execution_orders").upsert(
    {
      workspace_id: workspace.id,
      execution_date: parsed.data.date,
      ordered_item_ids: normalizedIds,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "workspace_id, execution_date" }
  );

  if (error) return { ok: false, error: error.message };

  revalidateTodayData();
  return { ok: true, message: "บันทึกลำดับการเรียนวันนี้แล้ว" };
}

const resetOrderSchema = z.object({
  date: dateString,
});

/**
 * Resets the daily execution order back to the default order generated by the study plan.
 */
export async function resetDailyExecutionOrder(
  input: z.infer<typeof resetOrderSchema>
): Promise<ActionResult> {
  const parsed = resetOrderSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "ข้อมูลไม่ถูกต้อง" };
  }

  const workspace = await getActiveWorkspace();
  if (!workspace) return { ok: false, error: "ไม่พบ workspace" };

  const supabase = await createServerSupabase();
  const { error } = await supabase
    .from("daily_execution_orders")
    .delete()
    .eq("workspace_id", workspace.id)
    .eq("execution_date", parsed.data.date);

  if (error) return { ok: false, error: error.message };

  revalidateTodayData();
  return { ok: true, message: "คืนลำดับตามแผนเรียบร้อยแล้ว" };
}

const studyNowSchema = z.object({
  planItemId: z.string().uuid().optional(),
  reviewTaskId: z.string().uuid().optional(),
  date: dateString,
});

/**
 * Switches execution immediately to the target task ("เรียนตอนนี้").
 * - If a previous task was studying, pauses it while strictly preserving its progress sessions.
 * - Does NOT mark previous task as completed.
 * - Sets the new target task to "studying".
 * - Moves target task to the front of execution order for today.
 */
export async function studyNow(
  input: z.infer<typeof studyNowSchema>
): Promise<ActionResult> {
  const parsed = studyNowSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "ข้อมูลไม่ถูกต้อง" };
  }

  const workspace = await getActiveWorkspace();
  if (!workspace) return { ok: false, error: "ไม่พบ workspace" };

  const supabase = await createServerSupabase();
  const targetPlanItemId = parsed.data.planItemId;

  if (targetPlanItemId) {
    // 1. Find any currently studying item in this workspace
    const { data: currentStudying } = await supabase
      .from("item_status_overrides")
      .select("plan_item_id, status")
      .eq("workspace_id", workspace.id)
      .eq("status", "studying");

    const previousItems = (currentStudying as Array<{ plan_item_id: string }> | null) ?? [];
    for (const prev of previousItems) {
      if (prev.plan_item_id !== targetPlanItemId) {
        // Pause previous task to preserve progress without marking completed
        await supabase
          .from("item_status_overrides")
          .update({ status: "paused", updated_at: new Date().toISOString() })
          .eq("workspace_id", workspace.id)
          .eq("plan_item_id", prev.plan_item_id);
      }
    }

    // 2. Ensure daily snapshot exists for the target item
    const { data: item } = await supabase
      .from("study_plan_items")
      .select("plan_version_id, date, lesson_from, lesson_to")
      .eq("id", targetPlanItemId)
      .eq("workspace_id", workspace.id)
      .maybeSingle();

    if (item) {
      const { data: existingSnap } = await supabase
        .from("daily_plan_snapshots")
        .select("id")
        .eq("workspace_id", workspace.id)
        .eq("snapshot_date", item.date)
        .maybeSingle();

      if (!existingSnap) {
        const { data: items } = await supabase
          .from("study_plan_items")
          .select("id, stable_external_id, subject, course_code, lesson_from, lesson_to, activity_type, target_minutes, priority, instructions")
          .eq("workspace_id", workspace.id)
          .eq("plan_version_id", item.plan_version_id)
          .eq("date", item.date)
          .order("priority", { ascending: true });

        await supabase.from("daily_plan_snapshots").insert({
          workspace_id: workspace.id,
          snapshot_date: item.date,
          plan_version_id: item.plan_version_id,
          payload: { items: items ?? [] },
          started_reason: "study_now",
        });
      }
    }

    // 3. Set target task to studying
    const { error: setStudyingError } = await supabase
      .from("item_status_overrides")
      .upsert(
        {
          workspace_id: workspace.id,
          plan_item_id: targetPlanItemId,
          status: "studying",
          actual_lesson_from: item?.lesson_from ?? null,
          actual_lesson_to: item?.lesson_to ?? null,
        },
        { onConflict: "plan_item_id" }
      );

    if (setStudyingError) {
      return { ok: false, error: setStudyingError.message };
    }

    // 4. Update daily_execution_orders to place target task at top of today's queue
    const { data: currentOrderData } = await supabase
      .from("daily_execution_orders")
      .select("ordered_item_ids")
      .eq("workspace_id", workspace.id)
      .eq("execution_date", parsed.data.date)
      .maybeSingle();

    const existingIds = normalizeOrderedIds(currentOrderData?.ordered_item_ids);
    const newOrder = [
      targetPlanItemId,
      ...existingIds.filter((id) => id !== targetPlanItemId),
    ];

    await supabase.from("daily_execution_orders").upsert(
      {
        workspace_id: workspace.id,
        execution_date: parsed.data.date,
        ordered_item_ids: newOrder,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "workspace_id, execution_date" }
    );
  }

  revalidateTodayData();
  return { ok: true, message: "เริ่มเรียนรายการที่เลือกแล้ว" };
}
